all:
  children:
    manager:
      hosts:
        manager:
      vars:
        ansible_user: Jayden
        ansible_ssh_private_key_file: '~/.ssh/ansible_id_rsa'
    worker:
      hosts:
        ansible-vm-2:
      vars:
        ansible_user: Jayden
        ansible_ssh_private_key_file: '~/.ssh/ansible_id_rsa'
