all:
  children:
    load_balancer:
      hosts:
        nginx:
    manager:
      hosts:
        swarm-master:
    worker:
      hosts:
        swarm-worker:
  vars:
    ansible_user: jenkins 
    ansible_ssh_private_key_file: '~/.ssh/id_rsa'
