---
- name: "Install Dependencies"
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - python3
    - python3-pip
    state: latest
    update_cache: true

- name: "Get Docker APT key"
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Add Docker APT repo"
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu bionic stable"
    state: present

- name: "Install Docker engine"
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: "Add user to Docker group"
  ansible.builtin.user:
    name: Jayden
    groups: docker
    append: yes

- name: "Install Docker with pip"
  pip:
    name: docker
    executable: pip3