---
- name: 'Join worker to docker swarm'
  docker_swarm:
    state: join
    advertise_addr: swarm-worker
    # join_token: "{{ hostvars['swarm-master']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    join_token: docker swarm join --token SWMTKN-1-1rzyvs97xbk64j9ean8kk49faqzvbxxyi8trj6vjysqo3rr6ph-d3e1a34ouhy116lhpq02nawea 10.154.0.9:2377
    remote_addrs: [ 'swarm-master:2377' ]